### ISSUE TITLE
OS packaged Certbot

### ISSUE THREAD

**Issue by Giga-Pudding** [ctrlaltcoop/certbot-dns-hetzner#23]
Hello,

for OS packaged versions of Certbot, there doesn't seem to be a python environment (in my case Debian 12).
/usr/lib/python3/dist-packages/certbot/

Is there any way to use this plugin with packaged versions of certbot? Maybe by simply copying files to the correct location?

Thanks & best regards!

**Comment by banchaa** [comment]
You could install python3-pip directly within Debian and then run ''pip install certbot-dns-hetzner'', but that is not recommended, because you might introduce broken dependencies with packages already installed by the system. 

1. **Uninstall the Debian package**: You can choose to uninstall the Debian package of Certbot to avoid confusion or conflicts, although this is not strictly necessary if you use a virtual environment. If you decide to uninstall it, you can do so with the following command:
   ```bash
   sudo apt-get remove certbot
   ```
2. **Install Python virtual environment tools**: If you haven't already installed the `virtualenv` package, you can do so with:
   ```bash
   sudo apt-get install virtualenv
   ```
3. **Create a virtual environment**: Choose a directory where you want to create your virtual environment and run:
   ```bash
   virtualenv -p python3 /path/to/your/virtualenv
   ```
   Replace `/path/to/your/virtualenv` with the path where you want to create the virtual environment.
4. **Activate the virtual environment**: Before installing Certbot and the plugin, you need to activate the virtual environment:
   ```bash
   source /path/to/your/virtualenv/bin/activate
   ```
5. **Install Certbot and the plugin**: Now that you're in the virtual environment, you can install Certbot and the Hetzner plugin using pip:
   ```bash
   pip install certbot certbot-dns-hetzner
   ```
